hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    #path("users/", include("users.urls"))
]

hw_project/quotes/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "quotes"
urlpatterns = [
    path("", views.main, name="root"),
    path("page/<int:page>/", views.main, name="root_paginate"),
    path('registration/', views.registration_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


    

hw_project/quotes/models.py
from django.db import models
from django.contrib.auth.models import User

class Quote(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length=100)
    tags = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

hw_project/users/models.py
from django.db import models

class Quote(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length=100)
    tags = models.CharField(max_length=200)
    

hw_project/quotes/forms.py
from django import forms
from .models import Quote

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

hw_project/users/forms.py
from django import forms
from .models import Quote

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

hw_project/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Create your views here.
from .utils import get_mongodb

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def registration_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('home')  # Перенаправлення на головну сторінку після реєстрації
    else:
        form = UserCreationForm()
    return render(request, 'registration.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')  # Перенаправлення на головну сторінку після входу
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8 mb-3">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    <a href="{% url 'registration' %}">Реєстрація</a>
                    <a href="{% url 'login' %}">Вхід</a>
                    <a href="/login" class="btn btn-primary">Logout</a>

                </p>
            </div>
        </div>


        {% block content %}
        {% endblock %}

    </div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}
        </div>
    </div>

        <div class="row header-box pt-3">
    <div class="col-md-8 mb-3">
        <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
        </h1>
    </div>
    <div class="col-md-4">
        <p>
            <a href="{% url 'registration' %}">Реєстрація</a>
            <a href="{% url 'login' %}">Вхід</a>
            <a href="/logout" class="btn btn-primary">Logout</a>
        </p>
    </div>
</div>


        {% endfor %}
        <nav>
        <ul class="pager">
            <li class="previous">
                <button type="secondary">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </button>
            </li>


            <li class="next">
                <button type="secondary">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                </button>
            </li>

        </ul>
    </nav>
    </div>
</div>

{% endblock %}

hw_project/quotes/templates/quotes/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вхід</title>
</head>
<body>
    <h2>Вхід</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Увійти</button>
    </form>
    <p>Не маєте облікового запису? <a href="{% url 'registration' %}">Зареєструватися</a></p>
</body>
</html>

hw_project/quotes/templates/quotes/password_reset_complete.html
<p>Ваш пароль було успішно скинуто. Тепер ви можете 
  <a href="{% url 'login' %}">увійти в систему</a> з новим паролем.</p>

hw_project/quotes/templates/quotes/password_reset_confirm.html
<form method="post">
  {% csrf_token %}
  {{ form.new_password1.label_tag }} {{ form.new_password1 }}
  {{ form.new_password2.label_tag }} {{ form.new_password2 }}
  <button type="submit">Змінити пароль</button>
</form>

hw_project/quotes/templates/quotes/password_reset_done.html
<p>На вашу адресу електронної пошти було надіслано листа з інструкціями щодо скидання паролю.</p>

hw_project/quotes/templates/quotes/password_reset_form.html
<form method="post">
  {% csrf_token %}
  {{ form.email.label_tag }} {{ form.email }}
  <button type="submit">Надіслати посилання для скидання паролю</button>
</form>

hw_project/quotes/templates/quotes/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Реєстрація</title>
</head>
<body>
    <h2>Реєстрація</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зареєструватися</button>
    </form>
    <p>Вже зареєстровані? <a href="{% url 'login' %}">Увійти</a></p>
</body>
</html>